name: Siddhartha Gunti
description: Things techie and product
meta_description: "Things techie and product"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://siddharthagunti.com'
google_analytics: 'UA-80891720-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://siddharthagunti.com'
author:         'Siddhartha Gunti'
